global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']

  - job_name: 'kitversity-app'
    static_configs:
      - targets: ['kitversity-app:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s

  - job_name: 'mysql'
    static_configs:
      - targets: ['kitversity-db:3306']

  - job_name: 'redis'
    static_configs:
      - targets: ['kitversity-redis:6379']